# Generated by Django 4.2.7 on 2025-04-09 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mfi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mfi',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='mfi')),
                ('file_output', models.FileField(upload_to='mfi')),
                ('log', models.TextField()),
                ('status', models.CharField(choices=[('started', 'started'), ('finished', 'finished'), ('error', 'error')], default='started', max_length=255)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='MfiLog',
        ),
    ]
