name: Create and publish a Docker image

on:
    push:
        branches:
            - '**'  # All branches

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Log in to the Container registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set image tag
                id: set-tag
                run: |
                    if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
                      echo "tag=latest" >> $GITHUB_OUTPUT
                    else
                      echo "tag=test" >> $GITHUB_OUTPUT
                    fi

            -   name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: ghcr.io/siegfriedkollotzek/dosiomics:${{ steps.set-tag.outputs.tag }}
